web-polls/joins/urls.py
__author__ = 'yuewanghuang'

from django.conf.urls import patterns, url
from joins import views

urlpatterns = patterns('',
                       url(r'^$', views.IndexView.as_view(), name='home'),
                       url(r'^(?P<ref_id>.*)$', views.ShareView.as_view(), name='share'),
                       #url(r'join/$','',name='join'),
)

web-polls/poll/urls.py
__author__ = 'yuewanghuang'

from django.conf.urls import patterns, url

from poll import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name="details"),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name="results"),
    url(r'^(?P<question_id>\d+)/votes/$', views.votes, name="votes"),
)

web-polls/web-polls/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import poll
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'postItTut1.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('poll.urls', namespace='polls')),
    url(r'^joins/', include('joins.urls', namespace='joins')),
)

web-polls/joins/models.py
from django.db import models

# Create your models here.

class Join(models.Model):
    email = models.EmailField(unique=True)
    ref_id = models.CharField(max_length=128,unique=True)
    ip_address = models.IPAddressField(default="0.0.0.0") #default needed for records already in the database
    date_join = models.DateTimeField('Date joined', auto_now_add=True, auto_now=False)
    date_edit = models.DateTimeField('Date edited', auto_now_add=False, auto_now=True)
    referrer = models.ForeignKey('self', related_name='Referred Me', null=True, blank=True) #ManytoOne relationship

    class Meta:
        unique_together = ('email','ref_id') #prevent duplicate

    def __str__(self):
        return self.email

web-polls/poll/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=100)
    pub_time = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return timezone.now() >= self.pub_time > timezone.now() - datetime.timedelta(days=1)
    # define some attributes for the method
    was_published_recently.admin_order_field='pub_time'
    was_published_recently.boolean = True
    was_published_recently.short_description = "Published Recently?"

class Answer(models.Model):
    question = models.ForeignKey(Question)
    answer_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.answer_text

web-polls/joins/forms.py
__author__ = 'yuewanghuang'
from django import forms
from .models import Join

class JoinForm(forms.ModelForm):
    class Meta:
        model = Join
        fields = ['email',]
    def addJoin(self):
        print "added a member!!"
# class JoinForm(forms.Form):
#     email = forms.EmailField()
#

web-polls/joins/views.py
from django.shortcuts import render
from django.views import generic
# Create your views here.
from .forms import JoinForm
from .models import Join

def get_ip(request):
    try:
        x_forward = request.META.get("HTTP_X_FORWARDED_FOR")
        if x_forward:
            ip = x_forward.split(",")[0]
        else:
            ip = request.META.get("REMOTE_ADDR")
    except:
        ip = '0.0.0.0'
    return ip

import uuid

def get_ref_id():
    ref_id = str(uuid.uuid4())[:11].replace('-','')
    print ref_id
    try:
        id_existed = Join.objects.get(ref_id=ref_id)
        get_ref_id() # try until a unit id is found
    except:
        return ref_id


class IndexView(generic.FormView):
    form_class = JoinForm
    template_name = "joins/index.html"

    def get(self, request, *args, **kwargs):
        try:
            self.referrer_id = request.session["ref_id"]
        except:
            self.referrer_id = None
        return super(IndexView, self).get(request, args, kwargs)

    def form_valid(self, form):
        #print form.__class__
        #form.save()
        email = form.cleaned_data['email']
        new_join_old, created = Join.objects.get_or_create(email=email)
        if created:
            new_join_old.ref_id = get_ref_id()
            new_join_old.ip_address = get_ip(self.request)
            if self.referrer_id:
                new_join_old.referrer = Join.objects.get(id=self.referrer_id)
            new_join_old.save()
        self.success_url = "/joins/%s" % new_join_old.ref_id
        return super(IndexView, self).form_valid(form)

class ShareView(generic.TemplateView):
# def home(request):
#     form = JoinForm(request.POST or None)
#     context = {'form': form}
#     template = "joins/index.html"
#  h   return render(request, template, context)
    #form_class = JoinForm
    template_name = "joins/share.html"

web-polls/poll/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
# Create your views here.
from poll.models import Question, Answer
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
import time

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        curr_time = timezone.now()
        return Question.objects.filter(pub_time__lte=curr_time).order_by('-pub_time')[:5]


class DetailView(generic.DetailView):
    model = Question #Question as the args, will automatically trigger 404 if not found
    template_name = 'polls/details.html'
    def get_queryset(self):
        curr_time = timezone.now()
        return Question.objects.filter(pub_time__lte=curr_time)

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

'''

def index(request):
    latest_question_list = Question.objects.order_by('-pub_time')[:5]
    #output = ', '.join([p.question_text for p in latest_question_list])
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def details(request, question_id):
    question = get_object_or_404(Question, pk=question_id)  # minimize coupling between model and view
    return render(request, 'polls/details.html', {'question': question})


def results(request, question_id):
    q = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': q})
'''


def votes(request, question_id):
    q = get_object_or_404(Question, pk=question_id)
    try:
        selected_answer = q.answer_set.get(pk=request.POST['answer'])
    except (KeyError, Answer.DoesNotExist):
        return render(request, 'polls/details.html', {'question': q, 'error_message': "You didn't select a vote!"})
        time.sleep(10)
    else:
        selected_answer.votes += 1
        selected_answer.save()
    return HttpResponseRedirect(reverse('polls:results', args=(q.id,)))

web-polls/joins/templates/joins/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Jumbotron Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/jumbotron//jumbotron.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="http://getbootstrap.com/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="http://getbootstrap.com/assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->

        {% block content%}


        {% endblock %}


      <hr>

      <footer>
        <p>&copy; Company 2014</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/examples/jumbotron/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

web-polls/joins/templates/joins/index.html
{% extends "joins/base.html" %}

{% block content %}
    <h1>Hello, welcome to Runner's Diet!</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

web-polls/joins/templates/joins/share.html
{% extends "joins/base.html" %}

{% block content %}
{{ ref_id }}
{% endblock %}

web-polls/poll/templates/polls/details.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}" />
    <title>details</title>
</head>
<body>
<h1>{{question.question_text}}</h1>
{% if error_message %} <p><strong>{{error_message}}</strong></p> {% endif %}
<form action= "{% url 'polls:votes' question.id %}" method="post">
    {% csrf_token %}
    {% for answer in question.answer_set.all %}
        <input type="radio" name="answer" id="answer{{forloop.counter}}" value="{{answer.id}}" />
        <label for="answer{{forloop.counter}}">{{answer.answer_text}}</label>
        <br />
    {% endfor %}
    <input type="submit" value="Vote" />
</form>
</body>
</html>

web-polls/poll/templates/polls/index.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}" />
    <title>Home</title>
</head>
<body>
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:details' question.id %}">{{question.question_text}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available now!</p>
{% endif %}
</body>
</html>

web-polls/poll/templates/polls/results.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}" />
    <title>results</title>
</head>
<body>
    <h1>{{question.question_text}}</h1>
    <ul>
        {% for answer in question.answer_set.all %}
            <li>{{answer.answer_text}} -- {{answer.votes}} vote{{answer.votes|pluralize}}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'polls:details' question.id %}">Vote again? </a>
</body>
</html>